### ISSUE TITLE
Shortening of labels

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#13]
When we capture clicks, sometimes the labels are too long. The labels can be long because the website itself has long labels or because we are recursively catching parent labels. Displaying these long labels makes the UI ugly and unusable. 1. We need to shorten the labels - show 10 characters+elipses (total 13 characters).

**Comment by kcramakrishna** [comment]
For task headings, wrap text for up to 3 lines. Truncate (with ellipses) beyond 3 lines

**Comment by yureshwar** [comment]
Fixed this in commit version c2379124b200730100b66f5264a77c4436ccbd3e
