### ISSUE TITLE
Add profanity detection to flow labels/titles

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#175]
Assess all below and pick one to implement:

https://rapidapi.com/collection/profanity-filter
https://rapidapi.com/raygorodskij/api/MicrosoftContentModerator
https://pypi.org/project/profanity-filter/
https://azure.microsoft.com/en-in/services/cognitive-services/content-moderator/
https://www.programmableweb.com/api/neutrino-bad-word-filter
https://www.purgomalum.com/
https://besedo.com/profanity-filters/
https://cloud.google.com/speech-to-text/docs/languages

**Comment by kcramakrishna** [comment]
Looks like google too has a profanity filter. https://cloud.google.com/speech-to-text/docs/languages 
We can explore this too.

**Comment by yureshwar** [comment]
After study and discussion, we have decided to use Microsoft Azure content moderator API.

https://docs.microsoft.com/en-us/azure/cognitive-services/content-moderator/

1. we will not use the spelling auto-correction feature as application-specific terms will be over ridden
2. we will silently auto remove the flagged words without consent from the user. This will be handled better in #216

**Comment by Keerthireddy01** [comment]
checked the profanity issue its working properly.
