### ISSUE TITLE
Calendar not getting highlighted during playback

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#182]
Calendar clickable action which got recorded during the recording is not getting highlighted during playback.

Ex: Add Program

**Comment by yureshwar** [comment]
This may have two issues which is at recording and while playback.

**Comment by yureshwar** [comment]
Fixed the issue in commit 0431156

**Comment by ragavankamaraju** [comment]
Calender is getting recorded and playback is also fine.
