### ISSUE TITLE
Scroll bar not appearing for action search results in plugin on Jira

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#20]
When we search for tasks, the right plugin pane displays possible results. These results are accompanied by a vertical scroll bar when there are numerous results. This vertical scroll bar is not being displayed right now.

**Comment by yureshwar** [comment]
Fixed this issue in commit version 3aadc2e625216d89bd62346e45a27a6e37570967
