### ISSUE TITLE
Multilingual input (voice) - Stage 1 of 3

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#206]
This requires extensive product design before implementation.

Step 1: We should be able to take voice input in any language, get the English translation, and provide appropriate results.

Step 2: Do we want to have the display language as the input language ? (We can have a button "English" which will display back in English. (Separate issue)

**Comment by kcramakrishna** [comment]
Google has easy APIs to accomplish this. We need to research and find the right APIs to make this task simple. (maybe look at Azure APIs too.)

**Comment by yureshwar** [comment]
The user can ask in any language and we will display it in that language. Our labels are currently all in English. Before we search for the term we will translate this phrase to English before sending to elasticsearch.
