### ISSUE TITLE
Dynamic sites not loading intermittently. 

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#26]
Some completely dynamic pages Eg: Angular applications with extra scripts do not load when the browser plugin is active. We have to deactivate the plugin or reload the page for normal page functionality.
The plugin should never hinder any web app performance whatsoever.

**Comment by kcramakrishna** [comment]
Explored the problem and found that the browser upgrade made some elements unnecessary. This means that, to capture clickable objects, we no longer need to extend html element prototypes in our sdk/plugin. 
Hence removing the extra code for detecting html elements.The flip side is that our plugin will not work for 

1. older versions of Chrome/browser (will fail at detecting anchor version) and/or 
2. Static html pages (server side page rendering). 

Verified that even older versions of our plugin/sdk does not help with redmine as Chrome update has broken our approach.

Solution: Have 2 different versions. One for dynamic sites and One static sites. These can be controlled with a flag. We can expose the flag in sdk to developers and to end users in the plugin. Dynamic will be the default approach for now. New issue for static site implementation - #28 .

**Comment by yureshwar** [comment]
Fixed the issue along with button recognize issue at commit number d86ab899
