### ISSUE TITLE
Plugin fails to correctly replay recorded actions (in some scenarios) 

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#27]
This issue is noticed in websites with menus popping up with mouse hover. It works in many cases but in some cases, though we are succeeding in recording the clicks, we are unable to 'play' them.

**Comment by kcramakrishna** [comment]
Problem: JS Framework adds extra attributes are added to 'clickable-objects' in hover menus. These are being recorded but during playback, these extra attributes are not present in the page since the hover menu has not been activated. Thus the target is not matching with what we have in our DB and hence we cannot invoke it.  
Solution: One approach is that we can try and play with the patter matching methods to see if we can alter it to match these items too. Another approach is to detect if the object had extra attributes than initial attributes. Another approach is to ask developers to add 'click invoke' functionality where they have only 'hover invoke'.

**Comment by yureshwar** [comment]
Fixed the issue under ca27a300
