### ISSUE TITLE
For dropdowns, the user input recorded during task creation is not being re-selected during playback. 

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#3]
Recorded click action of the option selected from the dropdown is not getting identified properly during playack for some dropdowns

**Comment by kcramakrishna** [comment]
We have changed behavior. Yuresh to describe and close this issue.

**Comment by yureshwar** [comment]
We are not recording anymore the option. We are recording the parent node which is of select HTML itselfself instead of option.
