### ISSUE TITLE
006 bug for https://dashboard.vantagecircle.co.in/

### ISSUE THREAD

**Issue by ragavankamaraju** [kcramakrishna/Digital_Assistant_Client#37]
label: 043
recorded sequence: Vantage Rewards-Manage Awards-Manage Budget-Manage Announcement
Enter a title-Search for Departments-span-select2-selection-select2-selection...
Open calendar-Open calendar-OK
comment: unable to find action
other comment: api lag

**Comment by yureshwar** [comment]
Clickable actions are sometimes getting detected and sometimes not getting detected.

**Comment by yureshwar** [comment]
Ignore this as vantagefit doesn't have enough customers yet.
