### ISSUE TITLE
Misplaced display of overlay

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#52]
Sometimes during playback, the overlay(highlight) display appears at the top left of the browser window instead of at the appropriate input field.

**Comment by yureshwar** [comment]
![image](https://user-images.githubusercontent.com/516516/95315374-0836af80-08b0-11eb-8c9b-da6ede2bbb73.png)

**Comment by yureshwar** [comment]
Fixed the issue in commit ccebf460
