### ISSUE TITLE
Change overlay usage during replay

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#53]
Currently, we have multiple input elements recorded for a particular task. During replay, all of these input elements are passed all at once to the introjs plugin. This creates various problems. We should change this logic. We should pass input elements to intorjs one-at-a-time. This will give us more control on the flow, reduce complexity and result in fewer bugs.

**Comment by yureshwar** [comment]
Came across a new issue and created #54

**Comment by yureshwar** [comment]
Fixed this in commit c2faaaaf
