### ISSUE TITLE
Solve timestamp discripency

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#69]
During recording, 
   1. We are saving the server timestamp along with the clicked node
   2. While displaying the clicked records in the right pane we are using browser timestamp to fetch records

This creates a problem when the browser/client system is not synced to UTC(internet time server). This can create problems on faulty clients and may also cause security issues. 

We need to reconcile this problem

**Comment by kcramakrishna** [comment]
Unable to replicate this.
