### ISSUE TITLE
Performance improvement during recording and playback

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#71]
Element positions change after every click. To handle this change of position we are being forced to reindex the entire page for every click. This is quite demanding on the processor. We need to figure out a way to reduce processor demand or to make it faster

**Comment by yureshwar** [comment]
This was introduced because of the fix for #70

**Comment by kcramakrishna** [comment]
Change wait time from 5s to lower value and test. Check for 1.5s, 2s, 2.5, 3, 3.5, 4s. See which sites have issues and based on the study, we can decide on which interval to finalise. Create new issue for following: We will also have a feature where this can be site configurable i.e. we can configure this manually per site or domain etc.

**Comment by yureshwar** [comment]
Resolved the issue long time back
