### ISSUE TITLE
Finding the correct node in the page for auto-invoking is taking too long.

### ISSUE THREAD

**Issue by kcramakrishna** [kcramakrishna/Digital_Assistant_Client#8]
When we are finding the action to be invoked, we have to iterate through all the available click-objects in the open page. This process is taking time - especially when there are a few hundred clickable objects in the page (Eg: Gmail - inbox). The delay is degrading the usability of the plugin. We need to reduce this search time.

**Comment by yureshwar** [comment]
We have resolved this by checking the weightage of the text.
