### ISSUE TITLE
Add "personal" tag for a recording node

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#82]
During recording when we click on an item it appears in the UDA panel. For the recorded node add a "personal" tag so that user can select whether it is a common button for all or specific to a user.

**Comment by yureshwar** [comment]
Technical changes involved:

1. Backend API for updating the clicked node data
2. Recording modification for allowing the user to select the personal tag
3. Displaying the data from updated node metadata in the recorded sequence
4. Comparing node functionality change during invoking recorded node

**Comment by ragavankamaraju** [comment]
tested on personal tag and found no issues
