### ISSUE TITLE
Recorded action under filter is not getting played back

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#93]
During recording if we select any filter values it is getting recorded but while played back getting unable to find action

Example: Label 071

**Comment by yureshwar** [comment]
As of now we are not going to record the clicks inside fiterdata popup. Need to fix them at later date.

Fixed the issue in commit 53605f3d

**Comment by ragavankamaraju** [comment]
Tested the filter issue and it is working fine and the clicks inside the filter button is not getting recorded as fixed.
