### ISSUE TITLE
Unable to see the message that highlights Please select the value and then click on play 

### ISSUE THREAD

**Issue by yureshwar** [kcramakrishna/Digital_Assistant_Client#94]
During playback on calendar it doenst hightight the field and doesn't show Please select the value and then click on play.

Example: Label 073

Under calender it doesn't show the highlight text.

**Comment by yureshwar** [comment]
Fixed the issue in commit 1f7cf327

**Comment by ragavankamaraju** [comment]
Tested the issue and the tool tip is visible now.
